##########################################################################################################################
# File automatically-generated by STM32forVSCode
##########################################################################################################################

# ------------------------------------------------
# Makefile used by STM32 For VSCode
# WARNING: This file can be overwritten when project settings change
# This Makefile can be used for CI/CD purposes to use it please make sure
# you setup an environment file with the following name: .stm32env.
# This file is sourced at the start of this Makefile and will be used to set
# compiler paths and other tooling paths.
# Do note that most variables can also be overwritten when invoking make
# e.g to change the optimization flags
# make -j 16 -f STM32Make.mk DEBUG=0 OPTIMIZATION=-Os
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
#   2023-06-16 - Added .stm32env file inclusion
#   2023-07-14 - Added file directory in the build folder
#							 - Added debug and release build options
#							 - Added multi platform support
#							 - Added help target
#							 - Added more documentation
# ------------------------------------------------

######################################
# Environment Variables
######################################
# Imports the environment file in which the compiler and other tooling is set
# for the build machine.
# This can also be used to overwrite some makefile variables
file_exists = $(or $(and $(wildcard $(1)),1),0)
ifeq ($(call file_exists,.stm32env),1)
  include .stm32env
endif

MAKEFILE_NAME = STM32Makenew.mk

######################################
# Target 
######################################
# This is the name of the embedded target which will be build
# The final file name will also have debug or release appended to it.
TARGET ?= FreeRTOS_Mail

#######################################
# Build directories
#######################################
# Build path can be overwritten when calling make or setting the environment variable
# in .stm32env

BUILD_DIRECTORY ?= build


######################################
# Optimization
######################################
# Optimization is switched based upon the DEBUG variable. If set to 1
# it will be build in debug mode with the Og optimization flag (optimized for debugging).
# If set to 0 (false) then by default the variable is used in the configuration yaml
# This can also be overwritten using the environment variable or by overwriting it
# by calling make with the OPTIMIZATION variable e.g.: 
# make -f $(MAKEFILE_NAME) -j 16  OPTIMIZATION=Os

# variable which determines if it is a debug build
DEBUG ?= 1

# debug flags when debug is defined
OPTIMIZATION ?= -Og

RELEASE_DIRECTORY = $(BUILD_DIRECTORY)/debug
ifeq ($(DEBUG),1)
  # Sets debugging optimization -Og and the debug information output
  OPTIMIZATION_FLAGS += -Og -g -gdwarf -ggdb
  $(TARGET) := $(TARGET)-debug
  RELEASE_DIRECTORY := $(BUILD_DIRECTORY)/debug
else
  OPTIMIZATION_FLAGS += $(OPTIMIZATION)
  $(TARGET) := $(TARGET)-release
  RELEASE_DIRECTORY := $(BUILD_DIRECTORY)/release
endif

######################################
# Definitions
######################################

# C definitions
C_DEFINITIONS =  \
-DDEBUG \
-DSTM32G071xx \
-DUSE_HAL_DRIVER


# C++ definitions
CXX_DEFINITIONS =  \
-DDEBUG \
-DSTM32G071xx \
-DUSE_HAL_DRIVER


# Assembly definitions
ASM_DEFINITIONS =  \


######################################
# Source Files
######################################


# C sources
C_SOURCES +=  \
../../../../../Drivers/BSP/STM32G0xx_Nucleo/stm32g0xx_nucleo.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_cortex.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dma.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dma_ex.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_exti.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_flash.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_flash_ex.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_gpio.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_pwr.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_pwr_ex.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rcc.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rcc_ex.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_tim.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_tim_ex.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c \
../../../../../Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c \
../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c \
../../../../../Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
../../../../../Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
../../../../../Middlewares/Third_Party/FreeRTOS/Source/list.c \
../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0/port.c \
../../../../../Middlewares/Third_Party/FreeRTOS/Source/queue.c \
../../../../../Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
../../../../../Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
../../../../../Middlewares/Third_Party/FreeRTOS/Source/timers.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
Src/app_freertos.c \
Src/main.c \
Src/stm32g0xx_hal_msp.c \
Src/stm32g0xx_hal_timebase_tim.c \
Src/stm32g0xx_it.c \
Src/system_stm32g0xx.c


CXX_SOURCES += \


# ASM sources
ASM_SOURCES +=  \
STM32CubeIDE/Application/Startup/startup_stm32g071rbtx.s



######################################
# Include Directories
######################################
# assembly includes
ASM_INCLUDES = \

# C includes
C_INCLUDES =  \
-I../../../../../Drivers/BSP/STM32G0xx_Nucleo \
-I../../../../../Drivers/CMSIS/Device/ST/STM32G0xx/Include \
-I../../../../../Drivers/CMSIS/Include \
-I../../../../../Drivers/STM32G0xx_HAL_Driver/Inc \
-I../../../../../Drivers/STM32G0xx_HAL_Driver/Inc/Legacy \
-I../../../../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
-I../../../../../Middlewares/Third_Party/FreeRTOS/Source/include \
-I../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0 \
-IDrivers/CMSIS/Device/ST/STM32G0xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/STM32G0xx_HAL_Driver/Inc \
-IDrivers/STM32G0xx_HAL_Driver/Inc/Legacy \
-IInc \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0



######################################
# Target System Flags
######################################
# The specific flags for the target system
# This sets things like hardware floating point and
# which version a specific Cortex-M processor is.

# cpu
CPU = -mcpu=cortex-m0plus

# fpu
FPU = 

# float-abi
FLOAT-ABI = 

# mcu
MCU_FLAGS = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)


######################################
# C and CPP Flags
######################################

# additional flags provided by the STM32 for VSCode configuration file
ADDITIONAL_C_FLAGS := 
ADDITIONAL_CXX_FLAGS := -feliminate-unused-debug-types 
ADDITIONAL_ASM_FLAGS := 

# Provides dependency information about header files
# This is used to recompile when a source file depends on
# information from a header file
DEPENDENCY_FLAGS = -MMD -MP -MF"$(@:%.o=%.d)" -MT $@

# Output a list file for the compiled source file.
# This is a representative of the source code in assembly
ASSEMBLER_LIST_OUTPUT_FLAG = -Wa,-a,-ad,-alms=$(call add_release_directory,$<,lst)

# Combining the compilation flags with language specific flags and MCU specific flags
C_FLAGS = \
$(MCU_FLAGS) \
$(C_DEFINITIONS) \
$(C_INCLUDES) \
$(OPTIMIZATION_FLAGS) \
$(DEPENDENCY_FLAGS) \
$(ADDITIONAL_C_FLAGS) \
$(ASSEMBLER_LIST_OUTPUT_FLAG)

CXX_FLAGS = \
$(MCU_FLAGS) \
$(CXX_DEFINITIONS) \
$(C_INCLUDES) \
$(OPTIMIZATION_FLAGS) \
$(DEPENDENCY_FLAGS) \
$(ADDITIONAL_CXX_FLAGS) \
$(ASSEMBLER_LIST_OUTPUT_FLAG)

ASM_FLAGS = $(C_FLAGS) $(ASM_DEFINITIONS) $(ADDITIONAL_ASM_FLAGS)

######################################
# Linker Flags
######################################
# linker script. This script will determine where certain sections will
# be place in memory.
# For a good reference look at: https://blog.thea.codes/the-most-thoroughly-commented-linker-script/
LINKER_SCRIPT := -TSTM32CubeIDE/STM32G071RBTX_FLASH.ld

# libraries
LIBRARIES := \
-lc \
-lm


# library directories
LIBRARY_DIRECTORIES := \


# Additional linker flags Flags from the yaml configuration file
# can be overwritten in the environment file
ADDITIONAL_LINKER_FLAGS ?= -specs=nosys.specs 

# Flags for outputting a map file
# -Wl,-Map= flag will output the map file to the specified file
# --cref will generate a cross reference table in the map file
LINKER_MAP_FLAGS ?= -Wl,-Map=$(addsuffix .map,$(basename $(@))),--cref

# Flags for cleaning up code at link time
# --gc-sections will eliminate dead code e.g. unused functions
LINKER_CLEAN_UP_FLAGS ?= -Wl,--gc-sections

LINKER_FLAGS = \
  $(MCU_FLAGS) \
  $(LINKER_SCRIPT) \
  $(LIBRARY_DIRECTORIES) \
  $(LIBRARIES) \
  $(LINKER_MAP_FLAGS) \
  $(LINKER_CLEAN_UP_FLAGS) \
  $(ADDITIONAL_LINKER_FLAGS)

#######################################
# Tools
#######################################
ARM_PREFIX = arm-none-eabi-
POSTFIX = "
PREFIX = "
# The gcc compiler bin path can be defined in the make command via ARM_GCC_PATH variable (e.g.: make ARM_GCC_PATH=xxx)
# or it can be added to the PATH environment variable.
# By default the variable be used from the environment file: .stm32env.
# if it is not defined 

ifdef ARM_GCC_PATH
    CC = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)gcc$(POSTFIX)
    CXX = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)g++$(POSTFIX)
    AS = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)gcc$(POSTFIX) -x assembler-with-cpp
    CP = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)objcopy$(POSTFIX)
    SZ = $(PREFIX)$(ARM_GCC_PATH)/$(ARM_PREFIX)size$(POSTFIX)
else
  CC ?= $(ARM_PREFIX)gcc
  CXX ?= $(ARM_PREFIX)g++$
  AS ?= $(ARM_PREFIX)gcc -x assembler-with-cpp
  CP ?= $(ARM_PREFIX)objcopy
  SZ ?= $(ARM_PREFIX)size
endif

HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

# Flash and debug tools
# Default is openocd however will be gotten from the 
OPENOCD ?= openocd

REMOVE_DIRECTORY_COMMAND = rm -fR
mkdir_function = mkdir -p $(1)
ifeq ($(OS),Windows_NT)
  convert_to_windows_path = $(strip $(subst /,\,$(patsubst %/,%,$(1))))
  REMOVE_DIRECTORY_COMMAND = cmd /c rd /s /q
  mkdir_function = cmd /e:on /c md $(call convert_to_windows_path,$(1))
endif

#######################################
# Build rules 
#######################################

remove_prefix_parent_dir = $(subst ../,,$(1))
add_release_directory = $(sort $(addprefix $(RELEASE_DIRECTORY)/,$(1)))
prefix_directory = $(sort $(addprefix $(2),$(1)))
convert_to_file_type = $(sort $(addsuffix .$(2),$(basename $(1))))
is_out_of_parent_file = $(if $(findstring ../,$(1)),$(1),)
filter_out_of_parent_files = $(foreach file,$(1),$(call is_out_of_parent_file,$(file)))

is_in_parent_file = $(if $(findstring ../,$(1)),,$(1))
filter_in_parent_files = $(foreach file,$(1),$(call is_in_parent_file,$(file)))

convert_in_parent_sources_to_objects = $(call add_release_directory,$(call convert_to_file_type,$(call filter_in_parent_files, $(1)),o))
add_release_directory_to_out_of_parent_files = $(call prefix_directory,$(call remove_prefix_parent_dir,$(1)),$(RELEASE_DIRECTORY)/external/)

OBJECTS = $(call convert_in_parent_sources_to_objects,$(C_SOURCES))
OUT_OF_PARENT_C_SOURCES = $(call filter_out_of_parent_files,$(C_SOURCES))
OBJECTS += $(sort $(call add_release_directory_to_out_of_parent_files,$(call convert_to_file_type,$(OUT_OF_PARENT_C_SOURCES),o)))

# objects for the different C++ file extensions
OBJECTS += $(call convert_in_parent_sources_to_objects,$(CXX_SOURCES))
OUT_OF_PARENT_CXX_SOURCES += $(call filter_out_of_parent_files,$(CXX_SOURCES))
OBJECTS += $(sort $(call add_release_directory_to_out_of_parent_files,$(call convert_to_file_type,$(OUT_OF_PARENT_CXX_SOURCES),o)))


# Objects for assembly code
OBJECTS += $(call convert_in_parent_sources_to_objects,$(ASM_SOURCES))
OUT_OF_PARENT_ASM_SOURCES += $(call filter_out_of_parent_files,$(ASM_SOURCES))
OBJECTS += $(sort $(call add_release_directory_to_out_of_parent_files,$(call convert_to_file_type,$(OUT_OF_PARENT_ASM_SOURCES),o)))




# Dependency files
DEPENDENCY_FILES = $(sort $(OBJECTS:.o=.d))


# the tree of folders which needs to be present based on the object files
BUILD_TREE = $(sort $(dir $(OBJECTS)))


# expect to have the source file and be able to convert it to a certain set of rules
define DIRECT_LINK_RULE_template =
$(1): $(2) | $$(BUILD_DIR) $$(BUILD_TREE)
	$$(CC) -c $$(C_FLAGS) $$< -o $$@
endef


#######################################
# Build Firmware
#######################################

FINAL_TARGET_NAME = $(RELEASE_DIRECTORY)/$(TARGET)
ELF_TARGET = $(FINAL_TARGET_NAME).elf


#######################################
# All
#######################################
# default action: build all
all: $(BUILD_TREE) 
all: $(FINAL_TARGET_NAME).elf
all: $(FINAL_TARGET_NAME).hex
all: $(FINAL_TARGET_NAME).bin

#######################################
# Build rules
#######################################

# C Files
$(RELEASE_DIRECTORY)/%.o: %.c $(MAKEFILE_NAME) | $(BUILD_DIR) $(BUILD_TREE)
	$(CC) -c $(C_FLAGS) $< -o $@

$(info sources:$(call add_release_directory_to_out_of_parent_files,$(call convert_to_file_type,$(OUT_OF_PARENT_C_SOURCES),o)),$(OUT_OF_PARENT_C_SOURCES))
$(foreach source,$(OUT_OF_PARENT_C_SOURCES),$(eval $(call DIRECT_LINK_RULE_template,$(call add_release_directory_to_out_of_parent_files,$(call convert_to_file_type,$(source),o)),$(source))))

# C++ files
$(RELEASE_DIRECTORY)/%.o: %.cpp $(MAKEFILE_NAME) | $(BUILD_DIR) $(BUILD_TREE)
	$(CXX) -c $(CXX_FLAGS) $< -o $@
$(RELEASE_DIRECTORY)/%.o: %.cc $(MAKEFILE_NAME) | $(BUILD_DIR) $(BUILD_TREE)
	$(CXX) -c $(CXX_FLAGS) $< -o $@
$(RELEASE_DIRECTORY)/%.o: %.cp $(MAKEFILE_NAME) | $(BUILD_DIR) $(BUILD_TREE)
	$(CXX) -c $(CXX_FLAGS) $< -o $@
$(RELEASE_DIRECTORY)/%.o: %.CPP $(MAKEFILE_NAME) | $(BUILD_DIR) $(BUILD_TREE)
	$(CXX) -c $(CXX_FLAGS) $< -o $@
$(RELEASE_DIRECTORY)/%.o: %.c++ $(MAKEFILE_NAME) | $(BUILD_DIR) $(BUILD_TREE)
	$(CXX) -c $(CXX_FLAGS) $< -o $@
$(RELEASE_DIRECTORY)/%.o: %.C $(MAKEFILE_NAME) | $(BUILD_DIR) $(BUILD_TREE)
	$(CXX) -c $(CXX_FLAGS) $< -o $@

# Assembly files
$(RELEASE_DIRECTORY)/%.o: %.s $(MAKEFILE_NAME) | $(BUILD_DIR) $(BUILD_TREE)
	$(AS) -c $(ASM_FLAGS) $< -o $@
$(RELEASE_DIRECTORY)/%.o: %.S $(MAKEFILE_NAME) | $(BUILD_DIR) $(BUILD_TREE)
	$(AS) -c $(ASM_FLAGS) $< -o $@

# ELF Firmware
$(RELEASE_DIRECTORY)/$(TARGET).elf: $(OBJECTS) $(MAKEFILE_NAME) | $(BUILD_TREE)
	$(CC) $(OBJECTS) $(LINKER_FLAGS) -o $@
	$(SZ) $@


$(FINAL_TARGET_NAME).hex: $(FINAL_TARGET_NAME).elf | $(BUILD_TREE)
	$(HEX) $< $@
  
$(FINAL_TARGET_NAME).bin: $(FINAL_TARGET_NAME).elf | $(BUILD_TREE)
	$(BIN) $< $@	
  
$(BUILD_DIR):
	$(call mkdir_function, $@)

$(BUILD_TREE):
	$(call mkdir_function, $@)


#######################################
# flash
#######################################
flash: $(FINAL_TARGET_NAME).elf
	$(OPENOCD) -f ./openocd.cfg -c "program $(FINAL_TARGET_NAME).elf verify reset exit"

#######################################
# erase
#######################################
erase: $(BUILD_DIRECTORY)/$(TARGET).elf
	$(OPENOCD) -f ./openocd.cfg -c "init; reset halt; stm32g0x mass_erase 0; exit"

#######################################
# clean up
#######################################

clean:
	$(REMOVE_DIRECTORY_COMMAND) $(BUILD_DIRECTORY)

#######################################
# custom makefile rules
#######################################


  
#######################################
# dependencies
#######################################
# $(DEPENDENCY_FILES):
# -include $(DEPENDENCY_FILES)

# *** EOF ***